services:
  database:
    image: postgres:18.0
    container_name: database
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INIT_ARGS: ${POSTGRES_INIT_ARGS}
    networks:
      - watchtower_network

  pgadmin:
    image: dpage/pgadmin4:9.9
    restart: always
    container_name: pgadmin4
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      - watchtower_network

  rust:
    build: .
    restart: always
    container_name: rust
    depends_on:
      - database
      - pgadmin
    volumes:
      - ../:/data/
    working_dir: /data
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    networks:
      - watchtower_network

networks:
  watchtower_network:
    driver: bridge